version: 2
root-markers:
  - .git/
lint-debounce: 1s
log-file: /tmp/efm.log
log-level: 1

tools:
  erb-formatter: &erb-formatter
    format-debounce: 2s
    format-stdin: true
    format-command: bundle exec erb-format --print-width=80 --stdin --tailwind-output-path=app/assets/builds/application.css

  rubyfmt: &rubyfmt
    format-stdin: true
    format-command: rubyfmt

languages:
  # ruby:
  #   - <<: *rubyfmt
  html:
    - <<: *erb-formatter
  eruby:
    - <<: *erb-formatter
