version: 2
root-markers:
  - .git/
lint-debounce: 1s
log-file: /tmp/efm.log
log-level: 1

tools:
  erb-formatter: &erb-formatter
    format-debounce: 2s
    format-stdin: true
    format-command: bundle exec erb-format --print-width=80 --no-split-classes --stdin

  rustywind: &rustywind
    format-stdin: true
    format-command: rustywind --stdin

  rubyfmt: &rubyfmt
    format-stdin: true
    format-command: rubyfmt

  biome: &biome
    format-stdin: true
    format-command: npx biome check --organize-imports-enabled=true --formatter-enabled=false --linter-enabled=false --stdin-file-path=file.ts --fix

languages:
  # ruby:
  #   - <<: *rubyfmt
  html:
    - <<: *erb-formatter
    - <<: *rustywind
  eruby:
    - <<: *erb-formatter
    - <<: *rustywind
  tsx:
    - <<: *rustywind
    - <<: *biome
  typescriptreact:
    - <<: *rustywind
    - <<: *biome
  typescript:
    - <<: *biome
