## Aliases ##

# General
alias la="ls -al"
alias ln="ln -v"
alias mkdir="mkdir -p"
alias grep="grep --color=auto"
alias cp="cp -r"
alias ..="cd ../"
alias ...="cd ../.."
alias ....="cd ../../.."
alias ltree="tree -L 1"
alias updatedb="/usr/libexec/locate.updatedb"

alias update="brew update; sleep 1; brew upgrade; sleep 1; brew cleanup; rustup update"

# Because I'm dumb
alias vim="nvim"

# Heroku
alias heroku_remote="heroku git:remote -a"

# tmux
alias tma="tmux att -t"
alias tmls="tmux ls"
alias t2="tmux -2"

# Bundler
alias b="bundle"
alias be="bundle exec"

# Rails
alias migrate="bin/rake db:migrate"
alias rake="bin/rake"

# Elixir
alias imix="iex -S mix"
alias server="iex -S mix phoenix.server"

# Git
alias g="git"
alias co="git checkout"
alias gcm="git checkout master"
alias gs="git status"
alias gpush="git push"
alias gpull="git pull"
alias gpoh="git push origin HEAD"
alias gsu="git submodule update"
alias gap="git add -p"
alias grm="git pull --rebase origin master"
alias grd="git pull --rebase origin development"
alias gupdate="git pull && git-clean -y"

alias light="export LIGHT_SHELL=1"
alias dark="export LIGHT_SHELL=0"

## User configuration ##

# History
export HISTSIZE=100000
export SAVEHIST=100000
export HISTFILE=~/.history
setopt SHARE_HISTORY

# Path VARs
export GOPATH="$HOME/code/go"
export PATH="/usr/local/bin:/usr/bin:/usr/local/bin:$PATH"
export PATH="$GOPATH/bin:$PATH"

# Start rbenv
if type rbenv > /dev/null; then
  eval "$(rbenv init -)"
fi

# Path Settings
# - MATTCASPER.local work/go/action_tracker_queue (master) $
setopt prompt_subst
autoload -Uz vcs_info
zstyle ':vcs_info:*' stagedstr 'M '
zstyle ':vcs_info:*' unstagedstr 'M '
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' actionformats '%F{5}[%F{2}%b%F{3}|%F{1}%a%F{5}]%f '
zstyle ':vcs_info:*' formats \
  '%F{5}(%F{2}%b%F{5}) %F{2}%c%F{3}%u%f'
zstyle ':vcs_info:git*+set-message:*' hooks git-untracked
zstyle ':vcs_info:*' enable git

precmd () {
  pwd=$(pwd)
  if [[ "${pwd}" != "/Users/mattcasper/code/work/procore" ]]; then
    vcs_info
  fi
}
PROMPT='%F{5} - %F{2}%M%F{5} %F{3}%3~ ${vcs_info_msg_0_}%f$ '

# Source FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Source and load Git completion
autoload -Uz compinit && compinit

# Z
source `brew --prefix`/etc/profile.d/z.sh

# Cargo
if [ -d "$HOME/.cargo" ]; then
  source "$HOME/.cargo/env"
fi

# Kiex
[ -f "$HOME/.kiex/scripts/kiex" ] && source "$HOME/.kiex/scripts/kiex"

# added by travis gem
[ -f "$HOME/.travis/travis.sh" ] && source "$HOME/.travis/travis.sh"

fpath+=~/.zfunc

# The next line updates PATH for the Google Cloud SDK.
if [ -f /Users/mattcasper/google-cloud-sdk/path.zsh.inc ]; then
  source '/Users/mattcasper/google-cloud-sdk/path.zsh.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /Users/mattcasper/google-cloud-sdk/completion.zsh.inc ]; then
  source '/Users/mattcasper/google-cloud-sdk/completion.zsh.inc'
fi

alias emacs="/usr/local/Cellar/emacs/25.3/bin/emacs -nw"

if [ -f "$HOME/.asdf/asdf.sh" ]; then
  source $HOME/.asdf/asdf.sh
fi


. $(brew --prefix asdf)/asdf.sh
